# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Charter' do
  pod 'MailingListParser', :path => '../MailingListParser'
  pod 'CollapsibleTextView', :path => '../CollapsibleTextView'
  pod 'GZIP', '~> 1.1.1'
  pod 'MMMarkdown', '~> 0.5.1'
  pod 'RealmSwift', '~> 0.98.0'
end
