fastlane_version "1.63.1"

default_platform :ios

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :appstore do
    cocoapods
    scan(scheme: "Charter")
    increment_build_number
    snapshot
    gym(scheme: "Charter") # Build your app - more options available
    deliver
  end

end
